
title: Benjamin Danglot
url: 'https://danglotb.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6




#Profile information
name: Dr Benjamin Danglot
tagline: PhD from University of Lille
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: danglot<at>inria<dot>fr
github: danglotb
gitlab: danglotb
twitter: '@BdanglotDanglot'

