baseURL = "https://danglotb.github.io/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Dr Benjamin Danglot"
    author = "Dr Benjamin Danglot"
    description = "Personal Website"
    copyright = ""

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "green"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Dr Benjamin Danglot"
        tagline = "PhD from University of Lille"
        location = "Davidson consulting, Rennes, France"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/danglotb"
            title = "GitHub"
        [[params.social.list]]
            icon = "ai ai-google-scholar"
            url = "https://scholar.google.com/citations?user=ZIj5dCgAAAAJ&hl=en"
            title = "Google Scholar"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/BdanglotDanglot"
            title = "Twitter"
        [[params.social.list]]
            icon = "fab fa-orcid"
            url = " https://orcid.org/0000-0001-9483-5743 "
            title = "Orcid"
        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/benjamin-danglot-18a05752/"
            title = "LinkedIn"		

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
        expand = false  # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "education"
        expand = false   # true for the section that is initially expanded
    #[[params.showInAccordion]]
    #    item = "publication"
    #[[params.showInAccordion]]
    #    item = "project"
    #[[params.showInAccordion]]
    #    item = "skill"
    #[[params.showInAccordion]]
    #   item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Tools development to measure the energy consumption (in joules) within the CI/CD. The goal is to identify practices and/or libraries that consume more energy, and propose to developers a new way of coding to reduce this energy consumption."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Research Engineer"
            dates = "December 2019 - August 2020"
            company = "Université Côte d'Azur (UCA)"
            details = "In the context of an initiative by Pole Emploi, 26 interns have been selected for a special program offering them a complete Fullstack developer training during 3 months. After these 3 months of courses, I joined them to build the first prototype of Development of a new kind social network. The goal is to bind together people looking for job opportunities, companies looking for specific profiles and training centers offering courses. I lead the group, being the product owner and the scrum master during 5 weeks. The source code is available in open-source [here](https://github.com/Bootcamp2020/skillful_network) (FR)."
            
        [[params.experience.list]]
            position = "PhD Candidate"
            dates = "December 2016 - November 2019"
            url = "https://www.stamp-project.eu/view/main/"
            company = "Inria Lille, Spirals team - STAMP-project"
            details = "Software Testing AMPlification (STAMP): is funded European Commission - H2020. STAMP works in DevOps and agile methods and aims at improving the value of testing at different step of the application's lifecycle. My research is mostly focused on unit test amplification. I exploited existing test methods to create variants to increase the mutation score, detects automatically behavioral change, etc. The manuscript is available [here](https://tel.archives-ouvertes.fr/tel-02396530)."

        [[params.experience.list]]
            position = "Research Engineer"
            dates = "September 2016 - November 2016"
            company = "Inria Lille, Spirals team"
            details = "Development of [nopol](http://github.com/SpoonLabs/nopol) is an automatic repair tool for java program. Nopol fixes conditional and pre-condition bug, using the test suite. A IDEA [plugin](https://github.com/SpoonLabs/nopol-ui-intellij) allows to developer to use nopol directly in their IDE."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"


        [[params.education.list]]
            degree = "Ph.D. in Computer Science"
            college = "University of Lille"
            dates = "2016 - 2019"
            thesis_title = " Automatic Unit Test Amplification For DevOps "
            thesis_url = "https://tel.archives-ouvertes.fr/tel-02396530"
        [[params.education.list]]
            degree = "M.S. in Computer Science"
            college = "University of Lille"
            dates = "2014 - 2016"
            thesis_title = "Correctness attraction: a study of stability of software behavior under runtime perturbation"
            thesis_url = "https://link.springer.com/article/10.1007/s10664-017-9571-8"
        [[params.education.list]]
            degree = "B.S. in Computer Science"
            college = "University of Lille"
            dates = "2011 - 2014"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 4"
            url = "#"
            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Baking"
